<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2Kdamgo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2Kdamgo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2Kdamgo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2Kdamgo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2Kdamgo\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2Kdamgo',
    'container.build_id' => '7b03fc11',
    'container.build_time' => 1582299032,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2Kdamgo');
